
import type { Personnel } from '../types';

export const samplePersonnel: Personnel[] = [
    {
        id: "10909274686",
        sicilNo: "101",
        adSoyad: "AHMET KÜÇÜKATEŞ",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '', 
        iseGirisTarihi: '2025-01-27',
        istenAyrilisNedeni: '',
        sgkNo: '10909274686',
        baseSalary: 25000,
        hourlyRate: 111.11, // Approx based on 25k/225h
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "12715155524",
        sicilNo: "102",
        adSoyad: "ERHAN ULAŞ",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2024-08-22',
        istenAyrilisNedeni: '',
        sgkNo: '12715155524',
        baseSalary: 25000,
        hourlyRate: 111.11,
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "12958069404",
        sicilNo: "103",
        adSoyad: "GÖKSEL HÜSEYİN GÜRLENKAYA",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2023-12-01',
        istenAyrilisNedeni: '',
        sgkNo: '12958069404',
        baseSalary: 36250,
        hourlyRate: 161.11,
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "10255243282",
        sicilNo: "104",
        adSoyad: "HATİCE KAYRETLİ",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2025-01-22',
        istenAyrilisNedeni: '',
        sgkNo: '10255243282',
        baseSalary: 25000,
        hourlyRate: 111.11,
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "18688056226",
        sicilNo: "105",
        adSoyad: "EMEL GÜLDÜ",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2024-11-21',
        istenAyrilisNedeni: '',
        sgkNo: '18688056226',
        baseSalary: 25000,
        hourlyRate: 111.11,
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "12517644752",
        sicilNo: "106",
        adSoyad: "CAN KÖSEOĞLU",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2025-07-26', // Note: Future date in PDF source, keeping as extracted
        istenAyrilisNedeni: '',
        sgkNo: '12517644752',
        baseSalary: 30000,
        hourlyRate: 133.33,
        bonuses: [],
        deductions: [],
        documents: []
    },
    {
        id: "10298249128",
        sicilNo: "107",
        adSoyad: "İLKER TAYA",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2025-04-21', // Note: Future date in PDF source
        istenAyrilisNedeni: '',
        sgkNo: '10298249128',
        baseSalary: 30000,
        hourlyRate: 133.33,
        bonuses: [],
        deductions: [],
        documents: []
    },
     {
        id: "11975990494",
        sicilNo: "108",
        adSoyad: "SAMET DURSUN",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2024-02-08',
        istenAyrilisNedeni: '',
        sgkNo: '11975990494',
        baseSalary: 33350,
        hourlyRate: 148.22,
        bonuses: [],
        deductions: [],
        documents: []
    },
     {
        id: "25069544678",
        sicilNo: "109",
        adSoyad: "ONAT DENİZ GÖRÜR",
        gorevi: "Personel",
        leaves: [],
        timeLogs: [],
        dogumTarihi: '',
        iseGirisTarihi: '2024-02-08',
        istenAyrilisNedeni: '',
        sgkNo: '25069544678',
        baseSalary: 26005.50,
        hourlyRate: 115.58,
        bonuses: [],
        deductions: [],
        documents: []
    }
];
